---
title: "simulateSimplePoissonPointProcesses"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simulateSimplePoissonPointProcesses}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(spatstat);
library(rSimSpatialProcessSampling);
```

```{r run}
#--simulate sets of simple Poisson point patterns over a range of intensity levels
#----no clustering

data(lstSamplingInfo);
#--simulation characteristics
#----number of simulations/intensity level
nsim=100; 
#----set the NMFS tow distance (window width)
wid = lstSamplingInfo$tdNMFS;                
#----set the max width (NMFS+BSFRF net widths + offset distance; window height)
hgt = lstSamplingInfo$nwNMFS+lstSamplingInfo$offset+lstSamplingInfo$nwBSFRF;
#--set the sampling "window"
win = spatstat.geom::owin(xrange=c(0,wid),yrange=c(0,hgt),unitname="km");
#--determine sampling window area (km^2)
aW  = wid*hgt;

#--define the list of simulation runs
lst = list(); 
#----set the mean number crab/km^2 for each simulation
mnCPUEs = seq(from=25,to=100,by=25);
#----loop over CPUEs
for (mnCPUE in mnCPUEs){
  message("Processing CPUE = ",mnCPUE);
  chr = as.character(mnCPUE);
  lst[[chr]] = spatstat.random::rpoispp(mnCPUE,win=win,nsim=nsim,drop=FALSE);
}
#--now do something with the simulation runs
```
